---
- name: copying example file app
  copy:
    src: *
    dest: /var/www/html/index.php
  become: true
  become_user: root

- name: copying app conf                       
  copy:
    src: app.conf
    dest: /etc/apache2/sites-available/app.conf
  become: true
  become_user: root

- name: check file exists.
  stat:
    path: /etc/apache2/sites-enabled/000-default.conf
  register: default

- name: Deleting Apache Config Default
  when: default.stat.exists == True
  file: 
    path: /etc/apache2/site-enabled/*
    state: absent
    force: yes
  become: true
  become_user: root

- name: Deleting Apache File Default
  when: default.stat.exists == True
  file:
    path: /var/www/html/index.html 
    state: absent
  become: true
  become_user: root

- name: Create symbolic link
  file:
    src: "/etc/apache2/sites-available/app.conf"
    dest: "/etc/apache2/sites-enabled/app.conf"
    state: link
  notify: restart apache2
